library(datarium)
library(tidyverse)

antismoking %>% write_csv("antismoking.csv")
anxiety %>% write_csv("anxiety.csv")
depression %>% write_csv("depression.csv")
genderweight %>% write_csv("genderweight.csv")
headache %>% write_csv("headache.csv")
heartattack %>% write_csv("heartattack.csv")
housetasks.raw %>% write_csv("housetasks.raw.csv")
jobsatisfaction %>% write_csv("jobsatisfaction.csv")
marketing %>% write_csv("marketing.csv")
mice2 %>% write_csv("mice2.csv")
mice %>% write_csv("mice.csv")
performance %>% write_csv("performance.csv")
properties %>% write_csv("properties.csv")
renalstone %>% write_csv("renalstone.csv")
selfesteem2 %>% write_csv("selfesteem2.csv")
selfesteem %>% write_csv("selfesteem.csv")
stress %>% write_csv("stress.csv")
taskachievment %>% write_csv("taskachievment.csv")
titanic.raw %>% write_csv("titanic.raw.csv")
weightloss %>% write_csv("weightloss.csv")
